# Generated by Django 3.2 on 2021-04-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_orderplaced_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
    ]
